version: '3.8'

services:
  nest-api-starter-production:
    container_name: nest-api-starter-production
    build:
      target: production
      context: .
      args:
        - PORT=${PORT:-8000}
    ports:
      - '${PORT:-8000}:${PORT:-8000}'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512m'
        reservations:
          cpus: '0.25'
          memory: '256m'

  nest-api-starter-dev:
    container_name: nest-api-starter-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT:-8000}
    ports:
      - '${PORT:-8000}:${PORT:-8000}'
      - '9229:9229'
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1.5g'
        reservations:
          cpus: '0.25'
          memory: '512m'
